'use client';
import {useEffect,useState} from 'react';
import {ShoppingCart,Trash2,Plus,Minus,FileText,Copy,Printer,MessageCircle,RefreshCw,Check} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {NativeSelect,NativeSelectOption} from '@/components/ui/native-select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription,DialogFooter} from '@/components/ui/dialog';
import {Member,money} from '@/lib/model';
import {Customer,Order,OrderState,orderStates,orderTotal,orderNumber,orderText,taxLabels} from '@/lib/orders-model';
import {api,saveBlob} from '@/lib/client';
import type {CartController} from './use-cart';

export default function OrdersPanel({cartState,user,notify,onCatalog}:{cartState:CartController;user:Member;notify:(s:string)=>void;onCatalog:()=>void}){
 const {cart,busy,loading,error,mutate,prepare,reload}=cartState;
 const [customer,setCustomer]=useState<Customer>(cart.customer),[rows,setRows]=useState<any[]>([]),[page,setPage]=useState(1),[listError,setListError]=useState(''),[listBusy,setListBusy]=useState(false),[selected,setSelected]=useState<Order|null>(null),[action,setAction]=useState<OrderState|null>(null),[note,setNote]=useState(''),[contact,setContact]=useState(''),[confirmed,setConfirmed]=useState(false),[saving,setSaving]=useState(false),[actionError,setActionError]=useState('');
 const can=(p:string)=>user.role==='owner'||user.permissions.includes(p);
 const customerKey=JSON.stringify(cart.customer);
 useEffect(()=>{setCustomer(cart.customer)},[customerKey]);
 async function load(){setListBusy(true);try{const r=await api('/api/orders?page='+page);setRows(r.items);setListError('')}catch(e){setListError((e as Error).message)}finally{setListBusy(false)}}
 useEffect(()=>{void load()},[page]);
 async function open(id:string){try{setSelected(await api('/api/orders?id='+encodeURIComponent(id)))}catch(e){notify((e as Error).message)}}
 async function create(){const order=await prepare(customer);if(order){setSelected(order);void load();notify('Liste kaydedildi. Müşteriye henüz gönderilmedi.')}}
 const beginAction=(state:OrderState)=>{setAction(state);setNote('');setContact('');setConfirmed(false);setActionError('')};
 async function changeState(){if(!selected||!action)return;setSaving(true);setActionError('');try{setSelected(await api('/api/orders',{id:selected.id,version:selected.version,state:action,note,customerContact:contact,confirmed}));setAction(null);void load()}catch(e){setActionError((e as Error).message)}finally{setSaving(false)}}
 async function copy(){if(!selected)return;try{await navigator.clipboard.writeText(orderText(selected));notify('Sipariş metni kopyalandı.')}catch{saveBlob(new Blob([orderText(selected)],{type:'text/plain;charset=utf-8'}),'siparis-'+orderNumber(selected.id)+'.txt');notify('Kopyalama desteklenmedi; metin dosyası indirildi.')}}
 const message=selected?orderText(selected):'';
 return <>
  <div className="page-heading"><div><p className="eyebrow">MÜŞTERİ ZİYARETİNDEN ONAYA</p><h1>Sepet ve siparişler</h1><p>{can('orders.view_all')?'Ekibin sipariş listeleri ve müşteri yanıtları.':'Kendi müşterileriniz ve sipariş listeleriniz.'}</p></div><Button variant="outline" onClick={onCatalog}><Plus/>Ürün ekle</Button></div>
  {can('orders.create')&&<section className="panel order-cart"><div className="order-section-heading"><h2><ShoppingCart size={20}/>Sepet <small>{cart.lines.length} farklı ürün</small></h2><Button variant="ghost" disabled={busy||loading} onClick={()=>void reload()}><RefreshCw/>Yenile</Button></div>
   {error&&<p role="alert" className="error-rows">{error}</p>}
   {loading?<p role="status">Sepet yükleniyor…</p>:!cart.lines.length?<div className="empty"><ShoppingCart/><h3>Birlikte bir sipariş hazırlayın</h3><p>Satış kataloğundan ürünleri sepete ekleyin.</p><Button onClick={onCatalog}>Kataloğa git</Button></div>:<>
    <div className="cart-lines">{cart.lines.map(l=><div className="cart-line" key={l.id}><div><b>{l.title}</b><small>{l.barcode||'Barkod belirtilmedi'} · Birim fiyat {money(l.price)}</small>{l.stock!==null&&l.quantity>l.stock&&<p className="order-warning">Son stok {l.stock.toLocaleString('tr-TR')} adet; teslim öncesinde kontrol edin.</p>}</div><div className="cart-quantity"><Button size="icon" variant="outline" disabled={busy||l.quantity<=1} aria-label={l.title+' adet azalt'} onClick={()=>void mutate({action:'quantity',id:l.id,quantity:l.quantity-1})}><Minus/></Button><Input key={l.id+':'+l.quantity} type="number" min={1} max={100000} aria-label={l.title+' adet'} defaultValue={l.quantity} disabled={busy} onBlur={e=>{const n=Number(e.target.value);if(n!==l.quantity)void mutate({action:'quantity',id:l.id,quantity:n})}}/><Button size="icon" variant="outline" disabled={busy||l.quantity>=100000} aria-label={l.title+' adet artır'} onClick={()=>void mutate({action:'quantity',id:l.id,quantity:l.quantity+1})}><Plus/></Button></div><strong>{money(l.price*l.quantity)}</strong><Button size="icon" variant="ghost" disabled={busy} aria-label={l.title+' sepetten çıkar'} onClick={()=>void mutate({action:'remove',id:l.id})}><Trash2/></Button></div>)}</div>
    <div className="cart-summary"><Button variant="outline" disabled={busy} onClick={()=>void mutate({action:'refresh'})}><RefreshCw/>Güncel katalog fiyatlarını al</Button><p>Liste toplamı <strong>{money(orderTotal(cart.lines))}</strong></p></div>
    <div className="form-grid order-customer"><label>Müşteri / yetkili adı<Input maxLength={120} value={customer.name} onChange={e=>setCustomer({...customer,name:e.target.value})}/></label><label>Firma<Input maxLength={160} value={customer.company} onChange={e=>setCustomer({...customer,company:e.target.value})}/></label><label>Telefon (isteğe bağlı)<Input type="tel" maxLength={40} value={customer.phone} onChange={e=>setCustomer({...customer,phone:e.target.value})}/></label><label>Listedeki fiyatlar<NativeSelect value={customer.tax} onChange={e=>setCustomer({...customer,tax:e.target.value as Customer['tax']})}><NativeSelectOption value="unspecified">Vergi durumunu seçin</NativeSelectOption><NativeSelectOption value="included">KDV dahil</NativeSelectOption><NativeSelectOption value="excluded">KDV hariç · KDV ayrıca hesaplanır</NativeSelectOption></NativeSelect></label><label className="full">Müşteriye gösterilecek not<Textarea maxLength={1500} value={customer.note} onChange={e=>setCustomer({...customer,note:e.target.value})} placeholder="Teslimat veya sipariş notu…"/></label></div>
    <p className="help-text">Adet, seçilen ürün/varyasyon birimi içindir. Koli varyasyonu seçtiyseniz 1 adet = 1 koli. Bu işlem stok ayırmaz, ödeme almaz ve Shopify’da sipariş oluşturmaz.</p>
    <div className="order-actions"><Button variant="outline" disabled={busy} onClick={()=>void mutate({action:'customer',customer}).then(r=>{if(r)notify('Müşteri bilgileri sepete kaydedildi.')})}>Taslağı kaydet</Button><Button disabled={busy||!customer.name.trim()||customer.tax==='unspecified'} onClick={()=>void create()}><FileText/>{busy?'Kaydediliyor…':'Sipariş listesini hazırla'}</Button></div>
   </>}
  </section>}
  <section className="panel order-history"><div className="order-section-heading"><h2>Sipariş geçmişi</h2><Button variant="ghost" disabled={listBusy} onClick={()=>void load()}><RefreshCw/>Yenile</Button></div>{listError?<p role="alert" className="error-rows">{listError}</p>:!rows.length?<p className="help-text">{listBusy?'Listeler yükleniyor…':'Henüz hazırlanmış bir sipariş listesi yok.'}</p>:<div className="order-list">{rows.map(r=><button className="order-list-row" key={r.id} onClick={()=>void open(r.id)}><span><b>{r.customerName}</b><small>{orderNumber(r.id)} · {r.actorName} · {new Date(r.createdAt).toLocaleDateString('tr-TR')}</small></span><span className={'order-state state-'+r.state}>{orderStates[r.state as OrderState]}</span><strong>{money(r.total)}</strong></button>)}</div>}<div className="pagination"><Button variant="outline" disabled={page===1||listBusy} onClick={()=>setPage(p=>p-1)}>Önceki</Button><span>{page}. sayfa</span><Button variant="outline" disabled={rows.length<30||listBusy} onClick={()=>setPage(p=>p+1)}>Sonraki</Button></div></section>
  <Dialog open={!!selected} onOpenChange={v=>{if(!v&&!saving){setSelected(null);setAction(null)}}}><DialogContent className="edit-dialog order-dialog"><DialogHeader><DialogTitle>Sipariş listesi {selected?orderNumber(selected.id):''}</DialogTitle><DialogDescription>{selected?.customer.name} · {selected&&orderStates[selected.state]}</DialogDescription></DialogHeader>{selected&&<>
   <div className="order-snapshot">{selected.lines.map(l=><div key={l.id}><span>{l.title}<small>{l.quantity.toLocaleString('tr-TR')} adet × {money(l.price)}</small></span><b>{money(l.quantity*l.price)}</b></div>)}<p>Liste toplamı <strong>{money(selected.total)}</strong></p><small>{taxLabels[selected.customer.tax]}</small>{selected.customer.note&&<p>{selected.customer.note}</p>}</div>
   <div className="order-actions"><Button variant="outline" onClick={()=>void copy()}><Copy/>Metni kopyala</Button><Button asChild variant="outline"><a href={'/orders/print?id='+encodeURIComponent(selected.id)} target="_blank" rel="noopener noreferrer"><Printer/>Yazdır / PDF</a></Button>{message.length<=5000?<Button asChild variant="outline"><a href={'https://wa.me/?text='+encodeURIComponent(message)} target="_blank" rel="noopener noreferrer"><MessageCircle/>WhatsApp’ta aç</a></Button>:<p className="help-text">Liste WhatsApp bağlantısı için uzun. Metni kopyalayın veya PDF olarak paylaşın.</p>}</div>
   <p className="help-text">WhatsApp’ta alıcıyı siz seçip gönderirsiniz. Düğmeyi açmak gönderildiği veya müşterinin onayladığı anlamına gelmez. Yazdır ekranından PDF olarak kaydedebilirsiniz.</p>
   <div className="order-actions">{selected.state==='prepared'&&<Button onClick={()=>beginAction('awaiting')}>Gönderdim · Yanıt bekleniyor</Button>}{selected.state==='awaiting'&&can('orders.record_approval')&&<><Button onClick={()=>beginAction('approved')}><Check/>Müşteri onayını kaydet</Button><Button variant="outline" onClick={()=>beginAction('rejected')}>Ret yanıtını kaydet</Button></>}{['prepared','awaiting','approved'].includes(selected.state)&&<Button variant="ghost" onClick={()=>beginAction('cancelled')}>Listeyi iptal et</Button>}</div>
   {action&&<div className="order-response"><h3>{orderStates[action]}</h3>{(action==='approved'||action==='rejected')&&<label className="field-label">Yanıt veren müşteri / yetkili<Input maxLength={120} value={contact} onChange={e=>setContact(e.target.value)}/></label>}<label className="field-label">{action==='awaiting'?'Gönderim notu (isteğe bağlı)':'Yanıt bilgisi / açıklama'}<Textarea maxLength={1000} value={note} onChange={e=>setNote(e.target.value)} placeholder="Örn. WhatsApp yanıtı, görüşme tarihi ve açıklama"/></label>{(action==='approved'||action==='rejected')&&<label className="order-confirm"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>Müşterinin yanıtını aldım. Bu kayıt benim beyanımdır; sistem tarafından doğrulanmış dijital onay değildir.</label>}{actionError&&<p role="alert" className="error-rows">{actionError}</p>}<div className="order-actions"><Button disabled={saving} onClick={()=>void changeState()}>Durumu kaydet</Button><Button variant="ghost" disabled={saving} onClick={()=>setAction(null)}>Vazgeç</Button></div></div>}
   <h3>Durum geçmişi</h3><ol className="order-events">{selected.history.map((e,i)=><li key={i}><b>{orderStates[e.state]}</b><small>{e.actorName} · {new Date(e.at).toLocaleString('tr-TR')}</small>{e.customerContact&&<p>Yanıt veren: {e.customerContact}</p>}{e.note&&<p>{e.note}</p>}</li>)}</ol>
  </>}<DialogFooter><Button variant="outline" onClick={()=>setSelected(null)} disabled={saving}>Kapat</Button></DialogFooter></DialogContent></Dialog>
 </>;
}
