'use client';
import {useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {api} from '@/lib/client';
import {Member} from '@/lib/model';
import type {ShopifyTransfer} from './use-shopify-transfer';
export function ShopifyPanel({user,notify,transfer}:{user:Member;notify:(s:string)=>void;transfer:ShopifyTransfer}){
 const [clientId,setId]=useState(''),[clientSecret,setSecret]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const info=transfer.info,sync=info?.sync;
 const stale=sync?.enabled&&(!sync.heartbeat||Date.now()-Date.parse(sync.heartbeat)>180000);
 const state=!info?'Kontrol ediliyor…':!info.connected?'Bağlantı bekleniyor':!sync.enabled?'Sunucu eşitlemesi etkin değil':stale?'Arka plan çalışanından sinyal bekleniyor':sync.error?'Yeniden deneme planlandı':sync.pending?'Eşitleme sürüyor':'Güncel';
 return <><div className="page-heading"><div><h1>Shopify bağlantısı</h1><p>Bir kez bağlayın. Ürünleri sunucu güncel tutsun.</p></div></div><div className="connection-grid"><section className="panel connection-card"><h2>{state}</h2><p>{info?.domain}</p><p>{sync?.products?.toLocaleString('tr-TR')||0} ürün · {sync?.variants?.toLocaleString('tr-TR')||0} varyasyon kaydı</p><p>{sync?.pending||0} işlem sırada</p><p>Son ürün güncellemesi: {sync?.lastProductSync?new Date(sync.lastProductSync).toLocaleString('tr-TR'):'Henüz yok'}</p><p>Değişiklik bildirimleri: {info?.webhooksRegistered?'Kuruldu':'Kurulum bekliyor'}</p>{(error||transfer.error)&&<p role="alert">{error||transfer.error}</p>}{user.role==='owner'&&<form className="form-grid" onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{await api('/api/shopify',{action:'connect',clientId,clientSecret});setId('');setSecret('');notify('Bağlantı doğrulandı; ilk eşitleme otomatik sıraya alındı.')}catch(err){setError((err as Error).message)}finally{setBusy(false)}}}><label>Client ID<Input required autoComplete="off" value={clientId} onChange={e=>setId(e.target.value)}/></label><label>Client secret<Input type="password" autoComplete="new-password" required value={clientSecret} onChange={e=>setSecret(e.target.value)}/></label><Button disabled={busy}>{busy?'Doğrulanıyor…':info?.connected?'Bağlantıyı güncelle':'Mağazayı bağla'}</Button></form>}</section><section className="panel connection-card"><h2>Nasıl çalışır?</h2><p>İlk aktarım bağlantıyla otomatik başlar. Yeni ürünler ve değişiklikler ayrı işlenir; ilk aktarımın bitmesini beklemez.</p><p>Sayfayı kapatsanız da kurulu sunucu zamanlayıcısı işleri sürdürür. Kesintilerde kayıtlı ilerlemeden otomatik devam edilir.</p><p>Ürün adı, açıklama, görsel, barkod, tür, marka ve stok Shopify’dan gelir. Yalnızca katalog fiyatını ve görünürlüğünü burada yönetirsiniz.</p><p>Yeni ürünler gizli ve fiyatsız gelir. Shopify’da silinen ürünler burada arşivlenir; eski sipariş kayıtları korunur.</p><p>Uygulama izinleri: ürün okuma ve stok okuma. Ürün veya fiyat değiştirme izni istenmez.</p><p>Yayın öncesinde kalıcı veritabanı, HTTPS adresi ve zamanlayıcı kurulmalıdır. Yalnızca dosyaları yüklemek arka plan hizmetini etkinleştirmez.</p></section></div></>;
}
