import {sqliteTable,text,integer,index,uniqueIndex} from 'drizzle-orm/sqlite-core';
export const products=sqliteTable('products',{
 id:text('id').primaryKey(),shopifyProductId:text('shopifyProductId'),shopifyVariantId:text('shopifyVariantId'),handle:text('handle').notNull(),title:text('title').notNull(),vendor:text('vendor').notNull().default(''),type:text('type').notNull().default(''),tags:text('tags').notNull().default(''),description:text('description').notNull().default(''),sku:text('sku').notNull().default(''),barcode:text('barcode').notNull().default(''),price:integer('price').notNull().default(0),catalogPrice:integer('catalogPrice'),comparePrice:integer('comparePrice'),stock:integer('stock'),visible:integer('visible').notNull().default(0),status:text('status').notNull().default('active'),image:text('image').notNull().default(''),source:text('source').notNull().default('csv'),version:integer('version').notNull().default(1),search:text('search').notNull().default(''),raw:text('raw').notNull().default('{}'),lastActor:text('lastActor').notNull().default('system'),lastBatch:text('lastBatch').notNull().default('sync'),seenAt:text('seenAt').notNull().default(''),updatedAt:text('updatedAt').notNull().default('')
},t=>[uniqueIndex('products_variant').on(t.shopifyVariantId),index('products_handle').on(t.handle),index('products_catalog').on(t.visible,t.status,t.title),index('products_vendor_type').on(t.vendor,t.type),index('products_barcode').on(t.barcode)]);
export const members=sqliteTable('members',{id:text('id').primaryKey(),email:text('email').notNull(),name:text('name').notNull(),role:text('role').notNull().default('staff'),permissions:text('permissions').notNull().default('[]'),active:integer('active').notNull().default(1),authId:text('authId'),createdAt:text('createdAt').notNull()},t=>[uniqueIndex('members_email').on(t.email),uniqueIndex('members_auth').on(t.authId)]);
export const settings=sqliteTable('settings',{key:text('key').primaryKey(),value:text('value').notNull()});
export const audit=sqliteTable('audit',{id:integer('id').primaryKey({autoIncrement:true}),batch:text('batch').notNull(),actor:text('actor').notNull(),productId:text('productId').notNull(),title:text('title').notNull(),before:text('before').notNull(),after:text('after').notNull(),afterVersion:integer('afterVersion').notNull(),createdAt:text('createdAt').notNull()},t=>[index('audit_batch').on(t.batch),index('audit_time').on(t.createdAt)]);
export const jobs=sqliteTable('jobs',{id:text('id').primaryKey(),kind:text('kind').notNull(),actor:text('actor').notNull(),state:text('state').notNull().default('staged'),payload:text('payload').notNull(),cursor:integer('cursor').notNull().default(0),total:integer('total').notNull().default(0),done:integer('done').notNull().default(0),errors:text('errors').notNull().default('[]'),leaseUntil:integer('leaseUntil').notNull().default(0),createdAt:text('createdAt').notNull(),updatedAt:text('updatedAt').notNull()},t=>[index('jobs_state').on(t.kind,t.state)]);
export const carts=sqliteTable('carts',{actor:text('actor').primaryKey(),version:integer('version').notNull().default(0),payload:text('payload').notNull().default('{}'),updatedAt:text('updatedAt').notNull()});
export const orders=sqliteTable('orders',{id:text('id').primaryKey(),actor:text('actor').notNull(),actorName:text('actorName').notNull(),customerName:text('customerName').notNull(),state:text('state').notNull().default('prepared'),total:integer('total').notNull(),payload:text('payload').notNull(),history:text('history').notNull().default('[]'),version:integer('version').notNull().default(1),createdAt:text('createdAt').notNull(),updatedAt:text('updatedAt').notNull()},t=>[index('orders_actor_time').on(t.actor,t.createdAt),index('orders_time').on(t.createdAt)]);
